apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace-stg.yaml
  - cert-manager-letsencrypt.yaml

patches:
  - path: patch-ingress.yaml
  - path: patch-configmap-env.yaml

namespace: petrvs-stg