# =====================================================================-
# API Version: kustomize.config.k8s.io/v1beta1
# Kind:       Kustomization
# Metadata:
#   Name:     production-overlay
# ----------------------------------------------------------------------
# Author:     erivandosena@gmail.com
# Created:    2025-04-21
# Version:    1.0.0
# ----------------------------------------------------------------------
# Description: Kustomize overlay configuration for production environment with:
#              - Base resources inclusion
#              - Namespace patching (petrvs-prd)
#              - Strategic patches for:
#                * ConfigMap environment variables
#                * Database initialization job
#                * Scheduler cronjob
#                * Ingress configuration
#              - Deployment/undeployment commands
# ----------------------------------------------------------------------
# Usage:

## test/validation
# kustomize build k8s-manifests-kustomize/overlays/production/
# kubectl apply -k k8s-manifests-kustomize/overlays/production/ --dry-run=client
# kustomize build k8s-manifests-kustomize/overlays/production/ | kubectl diff -f -

## deploy
# kubectl apply -k k8s-manifests-kustomize/overlays/production/
# kustomize build k8s-manifests-kustomize/overlays/production/ | kubectl apply -f -

## undeploy
# kubectl delete -k k8s-manifests-kustomize/overlays/production/ --wait=true
# kubectl delete namespace petrvs-prd --ignore-not-found=true
# kubectl get pv | grep Released | awk '{print $1}' | xargs -I{} kubectl delete pv {}
# =====================================================================-

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace-prd.yaml

patches:
- path: patch-configmap-env.yaml
- path: patch-job-petrvs-db-init.yaml
- path: patch-cronjob-scheduler.yaml
- path: patch-ingress.yaml

namespace: petrvs-prd
