---
# =====================================================================-
# API Version: v1
# Kind:       ConfigMap
# Metadata:
#   Name:     petrvs-env
# ----------------------------------------------------------------------
# Author:     erivandosena@gmail.com
# Created:    2025-04-23
# Version:    1.0.0
# ----------------------------------------------------------------------
# Usage:      Applied via kustomize patch
# =====================================================================-
apiVersion: v1
kind: ConfigMap
metadata:
  name: petrvs-env
data:
  APP_NAMESPACE: "petrvs-prd"
  MARIADB_MASTER_HOST: "mariadb-0.mariadb.petrvs-prd.svc.cluster.local"
  MARIADB_MASTER_WORKER1: "mariadb-1.mariadb.petrvs-prd.svc.cluster.local"
  MARIADB_MASTER_WORKER2: "mariadb-2.mariadb.petrvs-prd.svc.cluster.local"
  MARIADB_CLUSTER_ADDRESS: "gcomm://mariadb-0.mariadb.petrvs-prd.svc.cluster.local:4567"
