---
# =====================================================================-
# API Version: v1
# Kind:       ConfigMap
# Metadata:
#   Name:     petrvs-env
# ----------------------------------------------------------------------
# Author:     erivandosena@gmail.com
# Created:    2025-04-04
# Version:    1.0.0
# ----------------------------------------------------------------------
# Description: Variáveis de ambiente para a aplicação Petrvs, definindo
#              configurações específicas do ambiente de execução.
# ----------------------------------------------------------------------
# Usage:      kubectl apply -f configmap-petrvs-env.yaml
# =====================================================================-
apiVersion: v1
kind: ConfigMap
metadata:
  name: petrvs-env
data:
  # =======================
  # 📌 Core Laravel Configs
  # =======================
  APP_NAME: Petrvs
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: https://www.yourdomain.com.br
  TZ: America/Fortaleza
  FILESYSTEM_DRIVER: local
  APP_NAMESPACE: "petrvs"

  # =======================
  # 🔭 Telescope (debug e dev)
  # =======================
  TELESCOPE_ENABLED: "false"

  # =======================
  # 🌐 Domínios e Sessão
  # =======================
  CENTRAL_DOMAINS: www.yourdomain.com.br
  SESSION_DOMAIN: www.yourdomain.com.br
  SANCTUM_STATEFUL_DOMAINS: www.yourdomain.com.br:80,www.yourdomain.com.br:443
  SESSION_LIFETIME: "1200"
  SESSION_DRIVER: custom-database
  SESSION_CONNECTION: mysql
  SESSION_SAME_SITE: none
  SESSION_SECURE_COOKIE: "true"
  SESSION_HTTP_ONLY: "true"

  # =======================
  # 🔐 Security & Logging
  # =======================
  LOG_CHANNEL: stack
  LOG_LEVEL: error
  LOG_CONNECTION: log
  LOG_HOST: mariadb
  LOG_PORT: "3306"
  LOG_DATABASE: petrvs_logs_db
  LOG_TRAFFIC: "false"
  LOG_CHANGES: "false"
  LOG_ERRORS: "false"

  # =======================
  # Banco MySQL / MariaDB
  # =======================
  DB_CONNECTION: mysql
  DB_HOST: mariadb
  DB_PORT: "3306"
  DB_DATABASE: petrvs # petrvs_db
  DB_USERNAME: root
  MYSQL_DATABASE: petrvs # petrvs_db
  MYSQL_USER: petrvs
  MARIADB_AUTO_UPGRADE: "true"
  MARIADB_INITDB_SKIP_TZINFO: "1"
  MARIADB_REPLICATION_USER: "replicator"
  MARIADB_GALERA_CLUSTER: "ON"
  MARIADB_WSREP_PROVIDER: "/usr/lib/galera/libgalera_smm.so"
  MARIADB_MASTER_HOST: "mariadb-0.mariadb.petrvs.svc.cluster.local"
  MARIADB_MASTER_WORKER1: "mariadb-1.mariadb.petrvs.svc.cluster.local"
  MARIADB_MASTER_WORKER2: "mariadb-2.mariadb.petrvs.svc.cluster.local"
  MARIADB_CLUSTER_ADDRESS: "gcomm://mariadb-0.mariadb.petrvs.svc.cluster.local:4567"
  MARIADB_CLUSTER_NAME: petrvs_galera_cluster

  # =======================
  # 🧰 Redis
  # =======================
  REDIS_HOST: petrvs-redis
  REDIS_PORT: "6379"
  CACHE_DRIVER: redis
  QUEUE_CONNECTION: redis

  # =======================
  # 📧 E-mail SMTP
  # =======================
  MAIL_MAILER: smtp
  MAIL_HOST: ""
  MAIL_PORT: "465"
  MAIL_ENCRYPTION: ssl
  MAIL_FROM_ADDRESS: ""
  MAIL_FROM_NAME: "Petrvs"
  MAIL_USERNAME: ""
  SUPERUSER_EMAIL: super@user.com

  # =======================
  # ☁️ AWS S3 (opcional)
  # =======================
  AWS_DEFAULT_REGION: sa-east-1
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  # =======================
  # 📡 Broadcasting/Real-Time
  # =======================
  BROADCAST_DRIVER: log
  PUSHER_APP_CLUSTER: mt1
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

  # =======================
  # 🌱 Seeders dinâmicos por ambiente
  # =======================
  DB_SEEDER_LOCAL: DeployLocalSeeder
  DB_SEEDER_DEVELOPMENT: DeployDevSeeder
  DB_SEEDER_TESTING: DeployTestSeeder
  DB_SEEDER_STAGING: DeployStagingSeeder
  DB_SEEDER_PRODUCTION: DeployPRODSeeder

  # =======================
  # 🛡️ Proxy Trust (para Ingress)
  # =======================
  TRUSTED_PROXIES: "**"

  # =======================
  # 🏛️ Login Google/Gov.br/Microsoft
  # =======================
  LOGIN_TYPE: google
