---
# =====================================================================-
# API Version: autoscaling/v2
# Kind:       HorizontalPodAutoscaler
# Metadata:
#   Name:     petrvs-php-hpa
# ----------------------------------------------------------------------
# Author:     erivandosena@gmail.com
# Created:    2025-04-14
# Version:    1.0.0
# ----------------------------------------------------------------------
# Description: Configuração de escalonamento automático horizontal para
#              o deployment do backend PHP da aplicação Petrvs.
# ----------------------------------------------------------------------
# Usage:      kubectl apply -f hpa-petrvs-php.yaml
# =====================================================================-
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petrvs-php-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petrvs-php
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 1
        periodSeconds: 45
      selectPolicy: Max
