---
# =====================================================================-
# API Version: v1
# Kind:       Secret
# Metadata:
#   Name:     petrvs-env-secret
# ----------------------------------------------------------------------
# Author:     erivandosena@gmail.com
# Created:    2025-04-24
# Version:    1.0.0
# ----------------------------------------------------------------------
# Description: Secret contendo variáveis de ambiente sensíveis para a
#              aplicação Petrvs, como credenciais e tokens.
# ----------------------------------------------------------------------
# Usage:      kubectl apply -f secret-petrvs-env.yaml
# =====================================================================-
apiVersion: v1
kind: Secret
metadata:
  name: petrvs-secret-env
type: Opaque
data:
  APP_KEY: YmFzZTY0OlUzSThHMXZybzBxZEhxWUlsSGZRWVBTVHI4ZHFaSU9yTHQ1WHJkOHpFMFU9
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==                                 # root123
  MYSQL_PASSWORD: dXNlcjEyMw==                                      # user123
  DB_PASSWORD: cm9vdDEyMw==                                         # root123
  MARIADB_REPLICATION_PASSWORD: "cmVwbGljYXRvcjEyMw=="              # replicator123
  SST_USER: c3N0X3VzZXI=                                            # sst_user
  SST_PASSWORD: c3N0X3Bhc3N3b3JkMTIz                                # sst_password123
  REDIS_PASSWORD: cmVkaXMxMjM=                                      # redis123
  MAIL_PASSWORD: bWFpbDEyMw==                                       # mail123
  AWS_ACCESS_KEY_ID: "QVdTX0FDQ0VTU19LRVlfSURfQkFTRTY0"             # sample
  AWS_SECRET_ACCESS_KEY: "QVdTX1NFQ1JFVF9BQ0NFU1NfS0VZX0JBU0U2NA==" # sample
  GOOGLE_CLIENT_ID: <YOUR-GOOGLE_CLIENT_ID_BASE64>
  GOOGLE_CLIENT_SECRET: <YOUR-GOOGLE_CLIENT_SECRET_BASE64>
  GOVBR_CLIENT_ID: <YOUR-GOVBR_CLIENT_ID_BASE64>
  GOVBR_CLIENT_SECRET: <YOUR-GOVBR_CLIENT_SECRET_BASE64>
  SUPERUSER_PASSWORD: YWRtaW4xMjM=                                  # admin123
  SUPERUSER_CPF: MDAwMDAwMDAxOTE=                                   # 00000000191
