---
# =====================================================================-
# API Version: v1
# Kind:       Secret
# Metadata:
#   Name:     petrvs-tls
# ----------------------------------------------------------------------
# Author:     erivandosena@gmail.com
# Created:    2025-04-25
# Version:    1.0.0
# ----------------------------------------------------------------------
# Description: Secret do tipo TLS contendo certificado Wildcard/GlobalSign
# e chave privada para habilitar HTTPS na aplicação Petrvs.
# ----------------------------------------------------------------------
# Usage:      kubectl apply -f secret-tls.yaml
# =====================================================================-
apiVersion: v1
kind: Secret
metadata:
  name: petrvs-ca
type: Opaque
data:
  ca.crt: <YOUR_CA_CRT_BASE64>
---
apiVersion: v1
kind: Secret
metadata:
  name: petrvs-tls
type: kubernetes.io/tls
data:
  tls.crt: <YOUR_CRT_PEM_BASE64>
  tls.key: <YOUR_KEY_PEM_BASE64
